- hosts: all
  vars:
    app_name: "{{app_name}}"
    volumes: "{{volumes}}"
#远端的执行权限
  remote_user: root
  tasks:
  - name: mkdir -p
    with_items: "{{volumes}}"
    shell: mkdir -p /opt/gluster/{{app_name}}/{{item}}
#主机
- hosts: master
  vars:
    app_name: "{{app_name}}"
    volumes: "{{volumes}}"
    storage: 1Gi
#远端的执行权限
  remote_user: root
  tasks:
  - name: create gfs volume
    with_items: "{{volumes}}"
    shell: gluster volume create {{app_name}}-{{item}} k8s-master:/opt/gluster/{{app_name}}/{{item}} k8s-node-1:/opt/gluster/{{app_name}}/{{item}} k8s-node-2:/opt/gluster/{{app_name}}/{{item}} force
  - name: start volume
    with_items: "{{volumes}}"
    shell: gluster volume start {{app_name}}-{{item}}
