#主机
- hosts: master
#变量
  vars:
    app_name: "{{app_name}}"
    volumes: "{{volumes}}"
    destpath: "/home/yh/workspace/my-playbook/dest-gfs"
#远端的执行权限
  remote_user: root
  tasks:
  - name: kubectl pv
    with_items: "{{volumes}}"
    shell: kubectl delete -f {{destpath}}/{{app_name}}-{{item}}-pv.yaml
  - name: kubectl pvc
    with_items: "{{volumes}}"
    shell: kubectl delete -f {{destpath}}/{{app_name}}-{{item}}-pvc.yaml
  - name: kubectl namespace epsvc
    shell: kubectl delete -f {{destpath}}/{{app_name}}-epsvc.yaml && kubectl delete -f {{destpath}}/{{app_name}}-namespace.yaml
  - name: stop gfs
    with_items: "{{volumes}}"
    shell: gluster  --mode=script volume stop {{app_name}}-{{item}}
  - name: delete gfs dir and gfs
    with_items: "{{volumes}}"
    shell: gluster --mode=script volume delete {{app_name}}-{{item}}
#主机
- hosts: all
#变量
  vars:
    isDeldir: "{{isDeldir}}"
    app_name: "{{app_name}}"
    volumes: "{{volumes}}"
#远端的执行权限
  remote_user: root
  tasks:
  - name: del dir
    with_items: "{{volumes}}"
    when: isDeldir
    shell: rm -rf /opt/gluster/{{app_name}}/{{item}}

