- hosts: all
  vars:
    app_name: "{{app_name}}"
    volumes: "{{volumes}}"
#远端的执行权限
  remote_user: root
  tasks:
  - name: mkdir -p
    with_items: "{{volumes}}"
    shell: mkdir -p /opt/gluster/{{app_name}}/{{item}}
#主机
- hosts: master
  vars:
    app_name: "{{app_name}}"
    volumes: "{{volumes}}"
    storage: 1Gi
    homepath: "/home/yh/workspace/my-playbook"
#远端的执行权限
  remote_user: root
  tasks:
  - name: create gfs volume
    with_items: "{{volumes}}"
    shell: gluster volume create {{app_name}}-{{item}} k8s-master:/opt/gluster/{{app_name}}/{{item}} k8s-node-1:/opt/gluster/{{app_name}}/{{item}} k8s-node-2:/opt/gluster/{{app_name}}/{{item}} force
  - name: start volume
    with_items: "{{volumes}}"
    shell: gluster volume start {{app_name}}-{{item}}
  - name: file namespace
    template: src=./template-gfs/gfs-namespace.yaml dest={{homepath}}/dest-gfs/{{app_name}}-namespace.yaml
  - name: file app ep svc
    template: src=./template-gfs/gfs-epsvc.yaml dest={{homepath}}/dest-gfs/{{app_name}}-epsvc.yaml
  - name: file pv
    with_items: "{{volumes}}"
    template: src=./template-gfs/gfs-pv.yaml dest={{homepath}}/dest-gfs/{{app_name}}-{{item}}-pv.yaml
  - name: file pvc
    with_items: "{{volumes}}"
    template: src=./template-gfs/gfs-pvc.yaml dest={{homepath}}/dest-gfs/{{app_name}}-{{item}}-pvc.yaml
  - name: kubectl namespace epsvc
    shell: kubectl create -f {{homepath}}/dest-gfs/{{app_name}}-namespace.yaml && kubectl create -f {{homepath}}/dest-gfs/{{app_name}}-epsvc.yaml
  - name: kubectl pv
    with_items: "{{volumes}}"
    shell: kubectl create -f {{homepath}}/dest-gfs/{{app_name}}-{{item}}-pv.yaml
  - name: kubectl pvc
    with_items: "{{volumes}}"
    shell: kubectl create -f {{homepath}}/dest-gfs/{{app_name}}-{{item}}-pvc.yaml
