apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-{{app_name}}-{{item}}-pv
  namespace: {{app_name}}
spec:
  capacity:
    storage: {{storage}}
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "gfs-{{app_name}}-endpoint"
    path: "{{app_name}}-{{item}}"
    readOnly: false
