kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gfs-{{app_name}}-{{item}}-pvc
  namespace: {{app_name}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{storage}}
