apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-jenkins-data-pv
  namespace: jenkins
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "gfs-jenkins-endpoint"
    path: "jenkins-data"
    readOnly: false
