apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-maven-repo-pv
  namespace: jenkins
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "gfs-maven-endpoint"
    path: "maven-repo"
    readOnly: false
