---
kind: List
apiVersion: v1
items:
- kind: Endpoints
  apiVersion: v1
  metadata:
    name: gfs-maven-endpoint
    namespace: jenkins
  subsets:
  - addresses:
    - ip: 192.168.229.8
    ports:
    - port: 1
- kind: Service
  apiVersion: v1
  metadata:
    name: gfs-maven-endpoint
    namespace: jenkins
  spec:
    ports:
      - port: 1
