apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-mysql-data-pv
  namespace: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "gfs-mysql-endpoint"
    path: "mysql-data"
    readOnly: false
